### ISSUE TITLE
Dropdowns beyond 1 level

### ISSUE THREAD

**Issue by pless84** [tomhrtly/BulmaWP#1]
I get this when I have more than 1 level of dropdowns.
Can I make it so they go right or left of the main menu?
![screen shot 2019-01-09 at 10 14 50](https://user-images.githubusercontent.com/324145/50889201-af469880-13f7-11e9-89a8-2159f09147aa.png)

**Comment by tomhrtly** [comment]
There is an inline script added in the back-end [(see here)](https://github.com/tomhrtly/bulmawp/blob/master/src/functions.php#L176-L194) which stops users from adding multi level menus as unfortunately this isn't supported with Bulma out of the box [(see here)](https://github.com/jgthms/bulma/issues/1404).

I'm currently working on building an extension for the framework which will allow multi level menus, will post a link to the repo here when it's finished.
