### ISSUE TITLE
How to create stylesheet?

### ISSUE THREAD

**Issue by jrmhaig** [tomhrtly/BulmaWP#4]
Thanks for this starter theme. I was just in the process of trying to create it myself from scratch before I found it.

Please excuse what is probably a very simple question but I am unfamiliar with Wordpress.

What is the correct way to get the CSS into the theme? I found the sass file at `assets/sass/style.sass` but no indication on how to compile this to a css file. I followed [these instructions](https://torquemag.io/2017/06/start-using-sass-wordpress-npm-scripts/) and came up with [these changes](https://github.com/tomhrtly/bulmawp/compare/master...jrmhaig:master) so I can now call:

```bash
npm run css
```

to generate `assets/css/style.css`. Is this the right thing to do or should Wordpress compile the SASS for me?

**Comment by tomhrtly** [comment]
You need to copy all the files inside the `src` directory into your WordPress theme, then create a package.json file with the correct dependencies and scripts to compile the Sass setup for you inside the `assets/src/sass` directory.

Your package.json seems correct to me, when you run your script is the Sass file being compiled into your `assets/css` directory?

WordPress does not come with a Sass compiler out of the box, this is something that should be done using the command line with your npm scripts.

**Comment by jrmhaig** [comment]
Thank you for the clarification. Yes, the css file ends up in `assets/css`.
