### ISSUE TITLE
CSS missing

### ISSUE THREAD

**Issue by paramaggarwal** [tomhrtly/BulmaWP#5]
All the documentation steps point to downloading a `zip` file and then uploading to WordPress - but it does not contain anything in the `assets/css` folder. It actually needs a build step which is not documented.

**Comment by tomhrtly** [comment]
Yes, you're correct this is an additional build step. I will create a PR to make sure this is better documented.

**Comment by paramaggarwal** [comment]
Thank you for making this. 👍
